# Plantilla generica de Alembic
revision = '137a3c27bd07'
down_revision = '623f1dee4276'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa



def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('polling_table', sa.Column('code', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('polling_table', 'code')
    # ### end Alembic commands ###
